use std::collections::HashMap;
use std::sync::Arc;
use tokio::sync::RwLock;
use tracing::{info, warn};

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Budget {
    pub team_id: String,
    pub monthly_limit: f32,
    pub current_spend: f32,
    pub savings_realized: f32, // New: Total money saved by FluxGate
    pub forecast: f32,
}

pub struct FinOpsEngine {
    pub budgets: Arc<RwLock<HashMap<String, Budget>>>,
}

impl FinOpsEngine {
    pub fn new() -> Self {
        let mut initial_budgets = HashMap::new();
        initial_budgets.insert("team-alpha".to_string(), Budget {
            team_id: "team-alpha".to_string(),
            monthly_limit: 1000.0,
            current_spend: 450.0,
            savings_realized: 124.50,
            forecast: 950.0,
        });

        Self {
            budgets: Arc::new(RwLock::new(initial_budgets)),
        }
    }

    /// Records spend and updates the budget forecast.
    pub async fn record_spend(&self, team_id: &str, amount: f32) {
        let mut budgets = self.budgets.write().await;
        if let Some(budget) = budgets.get_mut(team_id) {
            budget.current_spend += amount;
            budget.forecast = budget.current_spend / 0.5; // Simplified linear forecast

            info!("💸 [FINOPS] Spend Recorded for {}: ${:.4}. Current: ${:.2}, Forecast: ${:.2}", 
                  team_id, amount, budget.current_spend, budget.forecast);

            if budget.current_spend > budget.monthly_limit * 0.9 {
                warn!("⚠️ [FINOPS] Budget CRITICAL for {}: 90% threshold exceeded.", team_id);
            }
        }
    }

    /// Records the savings generated by arbitrage or distillation.
    pub async fn record_savings(&self, team_id: &str, amount: f32) {
        let mut budgets = self.budgets.write().await;
        if let Some(budget) = budgets.get_mut(team_id) {
            budget.savings_realized += amount;
            info!("💰 [FINOPS] ROI ALERT: FluxGate just saved {}: ${:.4}. Total Savings: ${:.2}", 
                  team_id, amount, budget.savings_realized);
        }
    }

    /// Checks if a request should be blocked based on budget limits.
    pub async fn check_budget(&self, team_id: &str) -> bool {
        let budgets = self.budgets.read().await;
        if let Some(budget) = budgets.get(team_id) {
            if budget.current_spend >= budget.monthly_limit {
                warn!("🚫 [FINOPS] Budget DEPLETED for {}. Blocking further requests.", team_id);
                return false;
            }
        }
        true
    }

    /// Attributes economic value to an interaction based on complexity and outcome.
    pub fn attribute_value(&self, _agent_id: &str, cost: f32, value_score: f32) -> f32 {
        let eva = (cost * value_score) * 1.5; // Formula for Economic Value Added
        info!("📈 [ECONOMIC_VALUE] Attributed ${:.4} in EVA to interaction.", eva);
        eva
    }
}
